# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin_stats:
      class: AppBundle\Controller\AdminStatsController
      calls:
          - [ setContainer, [ @service_container ]]

    logout_handler:
      class: AppBundle\Controller\LogoutHandler